# Generated by Django 4.2.5 on 2024-04-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hmembers",
            name="health_policy",
        ),
        migrations.AddField(
            model_name="hmembers",
            name="children",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hmembers",
            name="region",
            field=models.CharField(
                choices=[
                    ("southwest", "Southwest"),
                    ("southeast", "Southeast"),
                    ("northwest", "Northwest"),
                    ("northeast", "Northeast"),
                ],
                default="southeast",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="hmembers",
            name="smoker",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hmembers",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                db_column="sex",
                max_length=10,
            ),
        ),
    ]
