# Generated by Django 4.2.5 on 2024-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_hmembers_health_policy_hmembers_children_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hmembers",
            name="region",
        ),
        migrations.RemoveField(
            model_name="hmembers",
            name="smoker",
        ),
        migrations.AlterField(
            model_name="agent",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=10
            ),
        ),
    ]
