# Generated by Django 4.2.5 on 2024-04-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_hmembers_region_remove_hmembers_smoker_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hmembers",
            name="children",
        ),
    ]
