# Generated by Django 4.2.5 on 2024-04-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_hmembers_children"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiclepolicy",
            name="created_by",
        ),
    ]
