# Generated by Django 4.2.5 on 2024-04-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_vehiclepolicy_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclepolicy",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.agent",
                verbose_name="Agent",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepolicy",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.staff",
                verbose_name="Staff",
            ),
        ),
    ]
