# Generated by Django 4.2.5 on 2024-04-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_vehiclepolicy_agent_alter_vehiclepolicy_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimapproval",
            name="claim_request",
        ),
        migrations.RemoveField(
            model_name="claimapproval",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="claimrequest",
            name="health_policy",
        ),
        migrations.RemoveField(
            model_name="claimrequest",
            name="vehicle_policy",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="health_plan",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="office",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="user",
        ),
        migrations.DeleteModel(
            name="HMembers",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="health_policy",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="vehicle_policy",
        ),
        migrations.DeleteModel(
            name="ClaimApproval",
        ),
        migrations.DeleteModel(
            name="ClaimRequest",
        ),
        migrations.DeleteModel(
            name="HealthPolicy",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
