# Generated by Django 4.2.5 on 2024-04-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_remove_claimapproval_claim_request_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "npersons",
                    models.IntegerField(verbose_name="Number of Persons Covered"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Policy Amount"
                    ),
                ),
                ("appldate", models.DateField(verbose_name="Application Date")),
                ("penddate", models.DateField(verbose_name="Policy End Date")),
                ("approval", models.BooleanField(verbose_name="Approval Status")),
                ("appdate", models.DateField(verbose_name="Approval Date")),
                ("comment", models.TextField()),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "health_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.healthplan",
                        verbose_name="Health Plan",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.office",
                        verbose_name="Office",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.staff",
                        verbose_name="Staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Late Fee",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Razorpay Order ID",
                    ),
                ),
                (
                    "health_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.healthpolicy",
                        verbose_name="Health Policy",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.staff",
                        verbose_name="Staff",
                    ),
                ),
                (
                    "vehicle_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.vehiclepolicy",
                        verbose_name="Vehicle Policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="HMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        db_column="sex",
                        max_length=10,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="member_photos/"
                    ),
                ),
                (
                    "health_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="home.healthpolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClaimRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reports", models.TextField()),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=100)),
                ("ifsc_code", models.CharField(max_length=15)),
                ("claim_date", models.DateField()),
                (
                    "health_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_claims",
                        to="home.healthpolicy",
                    ),
                ),
                (
                    "vehicle_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_claims",
                        to="home.vehiclepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Request",
                "verbose_name_plural": "Claim Requests",
            },
        ),
        migrations.CreateModel(
            name="ClaimApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(max_length=50, verbose_name="Approval Status"),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Approved Amount"
                    ),
                ),
                ("approval_date", models.DateField(verbose_name="Approval Date")),
                (
                    "claim_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="home.claimrequest",
                        verbose_name="Request Number",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.staff",
                        verbose_name="Staff ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Approval",
                "verbose_name_plural": "Claim Approvals",
            },
        ),
    ]
