# Generated by Django 4.2.5 on 2024-04-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_healthpolicy_payment_hmembers_claimrequest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimrequest",
            name="health_policy",
        ),
        migrations.RemoveField(
            model_name="claimrequest",
            name="vehicle_policy",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="health_plan",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="office",
        ),
        migrations.RemoveField(
            model_name="healthpolicy",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="hmembers",
            name="health_policy",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="health_policy",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="vehicle_policy",
        ),
        migrations.DeleteModel(
            name="ClaimApproval",
        ),
        migrations.DeleteModel(
            name="ClaimRequest",
        ),
        migrations.DeleteModel(
            name="HealthPolicy",
        ),
        migrations.DeleteModel(
            name="HMembers",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
