# Generated by Django 4.2.5 on 2024-05-01 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_healthpolicy_appdate_alter_payment_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimapproval",
            name="approved_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Approved Amount",
            ),
        ),
        migrations.AlterField(
            model_name="healthpolicy",
            name="appdate",
            field=models.DateField(
                default=datetime.date(2024, 5, 1), verbose_name="Approval Date"
            ),
        ),
    ]
