# Generated by Django 4.2.5 on 2024-05-03 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_claimapproval_approved_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimapproval",
            name="staff",
        ),
        migrations.AlterField(
            model_name="healthpolicy",
            name="appdate",
            field=models.DateField(
                default=datetime.date(2024, 5, 3), verbose_name="Approval Date"
            ),
        ),
    ]
