# Generated by Django 4.2.5 on 2024-05-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_remove_claimapproval_staff_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClaimApproval",
        ),
    ]
