# Generated by Django 4.2.5 on 2024-05-07 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_claimapproval_delete_claimapprovals"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="place",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="healthpolicy",
            name="appdate",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Approval Date"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
