# Generated by Django 4.2.5 on 2024-05-08 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_remove_blogpost_seller_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("place", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("pin", models.CharField(max_length=6)),
                ("phone", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                ("qualification", models.CharField(max_length=100)),
                ("aadhar", models.CharField(max_length=12, unique=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="agent_photos/"),
                ),
                ("registration_date", models.DateField()),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=20)),
                ("creation_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=10, unique=True)),
                ("aadhaar", models.CharField(max_length=12, unique=True)),
                ("address", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/customer_images/"
                    ),
                ),
                ("place", models.CharField(max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ptype", models.CharField(max_length=100)),
                (
                    "ypremium",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Yearly Premium"
                    ),
                ),
                (
                    "incper",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Coverage Increase Percentage",
                    ),
                ),
                (
                    "maxamt",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Maximum Amount"
                    ),
                ),
                ("specification", models.TextField()),
                ("uptoage", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HealthPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "npersons",
                    models.IntegerField(verbose_name="Number of Persons Covered"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Policy Amount"
                    ),
                ),
                ("appldate", models.DateField(verbose_name="Application Date")),
                ("penddate", models.DateField(verbose_name="Policy End Date")),
                (
                    "approval",
                    models.BooleanField(default=True, verbose_name="Approval Status"),
                ),
                (
                    "appdate",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Approval Date"
                    ),
                ),
                ("comment", models.TextField(default=None, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "health_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.healthplan",
                        verbose_name="Health Plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                ("officeid", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.TextField()),
                ("place", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("pin", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("regdate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_name", models.CharField(max_length=200)),
                ("sum_assurance", models.PositiveIntegerField()),
                ("premium", models.PositiveIntegerField()),
                ("tenure", models.PositiveIntegerField()),
                ("creation_date", models.DateField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("place", models.CharField(max_length=100)),
                ("pin", models.CharField(max_length=6)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
                ),
                (
                    "office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.office",
                        verbose_name="Office",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiclePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PType",
                    models.CharField(max_length=100, verbose_name="Premium Type"),
                ),
                (
                    "Ppercentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Premium Percentage",
                    ),
                ),
                ("sp", models.TextField(verbose_name="Specifications and Conditions")),
                ("depreciation", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="VehiclePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(max_length=20, verbose_name="Vehicle Number"),
                ),
                (
                    "vehicle_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Vehicle Value"
                    ),
                ),
                (
                    "engine_number",
                    models.CharField(max_length=50, verbose_name="Engine Number"),
                ),
                (
                    "chassis_number",
                    models.CharField(max_length=50, verbose_name="Chassis Number"),
                ),
                (
                    "vehicle_size",
                    models.CharField(max_length=50, verbose_name="Vehicle Size"),
                ),
                (
                    "vehicle_company",
                    models.CharField(max_length=100, verbose_name="Vehicle Company"),
                ),
                (
                    "vehicle_power",
                    models.CharField(max_length=50, verbose_name="Vehicle Power"),
                ),
                (
                    "manufacture_year",
                    models.IntegerField(verbose_name="Manufacture Year"),
                ),
                (
                    "vehicle_photo",
                    models.ImageField(
                        upload_to="vehicle_photos/", verbose_name="Vehicle Photo"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(max_length=50, verbose_name="Vehicle Type"),
                ),
                (
                    "policy_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Policy Amount"
                    ),
                ),
                ("policy_date", models.DateField(verbose_name="Policy Date")),
                ("policy_end_date", models.DateField(verbose_name="Policy End Date")),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.office",
                        verbose_name="Office",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.staff",
                        verbose_name="Staff",
                    ),
                ),
                (
                    "vehicle_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.vehicleplan",
                        verbose_name="Vehicle Plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("admin_comment", models.CharField(default="Nothing", max_length=200)),
                ("asked_date", models.DateField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=100)),
                ("creation_date", models.DateField(auto_now=True)),
                (
                    "Policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.policy"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Late Fee",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Razorpay Order ID",
                    ),
                ),
                (
                    "health_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.healthpolicy",
                        verbose_name="Health Policy",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.staff",
                        verbose_name="Staff",
                    ),
                ),
                (
                    "vehicle_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.vehiclepolicy",
                        verbose_name="Vehicle Policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="HMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        db_column="sex",
                        max_length=10,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="member_photos/"
                    ),
                ),
                (
                    "region",
                    models.IntegerField(
                        choices=[
                            (0, "Northeast"),
                            (1, "Northwest"),
                            (2, "Southeast"),
                            (3, "Southwest"),
                        ],
                        null=True,
                    ),
                ),
                ("smoker", models.BooleanField(null=True)),
                (
                    "health_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="home.healthpolicy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="healthpolicy",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.office",
                verbose_name="Office",
            ),
        ),
        migrations.AddField(
            model_name="healthpolicy",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.staff",
                verbose_name="Staff",
            ),
        ),
        migrations.CreateModel(
            name="ClaimRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reports", models.TextField()),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=100)),
                ("ifsc_code", models.CharField(max_length=15)),
                ("claim_date", models.DateField()),
                (
                    "health_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_claims",
                        to="home.healthpolicy",
                    ),
                ),
                (
                    "vehicle_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_claims",
                        to="home.vehiclepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Request",
                "verbose_name_plural": "Claim Requests",
            },
        ),
        migrations.CreateModel(
            name="ClaimApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(max_length=50, verbose_name="Approval Status"),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Approved Amount",
                    ),
                ),
                ("approval_date", models.DateField(verbose_name="Approval Date")),
                (
                    "claim_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="home.claimrequest",
                        verbose_name="Request Number",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Approval",
                "verbose_name_plural": "Claim Approvals",
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("views", models.IntegerField(default=0)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="home.staff",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
