# Generated by Django 4.2.5 on 2024-05-08 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_remove_hospital_activation_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hospital",
        ),
    ]
